### ISSUE TITLE
Interpolation issue - v1.000 Roman uni0304.case

### ISSUE THREAD

**Issue by kenmcd** [d-sargent/platypi#1]
Interpolation issue - v1.000 Roman uni0304.case
Version: v1.000 Roman (2024-01-17)
File: Platypi[wght].ttf
Glyph: /uni0304.case
Also affects all composites using this glyph.
Masters have different start points.

![2024-01-17_11-37-15](https://github.com/d-sargent/platypi/assets/844920/3c204b86-f98f-451d-ae47-1a4d45c2142c)

Love the font!

**Comment by d-sargent** [comment]
Thanks @kenmcd great pickup and thanks for the compliment! Now fixed.
