### ISSUE TITLE
lower case filenames

### ISSUE THREAD

**Issue by tomByrer** [d-sargent/platypi#10]
I'm not sure if the world would end if [mixed-case files are deployed on Windows then Linux](https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity), but OSes are not unified on how they are handled.
I usually advise folks to to always use lower-case to help prevent issues.

**Comment by d-sargent** [comment]
Hi @tomByrer I'm not exactly sure what you are asking here. If it is the font file names, I'm following the examples set out in the Google Fonts template. i.e. FontName.ttf and FontName-Italic.ttf
