### ISSUE TITLE
feature documentation?

### ISSUE THREAD

**Issue by tomByrer** [d-sargent/platypi#9]
What axes/variations/features does your font support?  I see some ligatures, anything else?

eg (kinda extreme example)
https://www.axis-praxis.org/specimens/nobotoflex

**Comment by d-sargent** [comment]
Hi @tomByrer it has a weight axis across Roman and Italic styles. 

In terms of features, it does have a selection of ligatures, and I aim to develop more extensive language support over the next few months.
